/**
 * 
 */
package com.tie.consume.ws;

import java.rmi.RemoteException;

import javax.xml.rpc.ServiceException;

import com.oracle.brm.cust.services.InfranetCUSTWebservicesServiceLocator;
import com.tie.model.Contract;

/**
 * @author Ahmed El-Deeb
 *
 */
public class ConsumeCustomerService {

	public String createCustomerService(Contract contract) {
		String xmlResponse = "";
		InfranetCUSTWebservicesServiceLocator serviceLocator = new InfranetCUSTWebservicesServiceLocator();
		String xmlRequest = "	<PCM_OP_CUST_CREATE_CUSTOMER_inputFlist>\r\n"
				+ "					<POID>0.0.0.1 /account 1 1</POID>\r\n"
				+ "					<END_T>1514761200</END_T>\r\n" + "					<NAMEINFO elem=\"0\">\r\n"
				+ "						<FIRST_NAME>Lagardere Travel Retail</FIRST_NAME>\r\n"
				+ "						<ZIP>75008</ZIP>\r\n" + "						<COUNTRY>France</COUNTRY>\r\n"
				+ "						<EMAIL_ADDR>lagardere@bac.com</EMAIL_ADDR>\r\n"
				+ "						<LAST_NAME>Dummy</LAST_NAME>\r\n"
				+ "						<ADDRESS>52, Avenue Foch</ADDRESS>\r\n"
				+ "						<CITY>Paris</CITY>\r\n" + "					</NAMEINFO>\r\n"
				+ "					<BILLINFO elem=\"0\">\r\n"
				+ "						<POID>0.0.0.1 /billinfo -1 0</POID>\r\n"
				+ "						<BILLINFO_ID>1 - Retail Revenue Sharing</BILLINFO_ID>\r\n"
				+ "						<PAYINFO elem=\"0\"></PAYINFO>\r\n"
				+ "						<BAL_INFO elem=\"0\"></BAL_INFO>\r\n"
				+ "						<PAY_TYPE>10001</PAY_TYPE>\r\n"
				+ "						<BILLING_SEGMENT>0</BILLING_SEGMENT>\r\n"
				+ "						<PARENT_FLAGS>0</PARENT_FLAGS>\r\n"
				+ "						<BILL_WHEN>1</BILL_WHEN>\r\n"
				+ "						<ACTG_TYPE>2</ACTG_TYPE>\r\n"
				+ "						<CURRENCY>48</CURRENCY>\r\n" + "					</BILLINFO>\r\n"
				+ "					<BILLINFO elem=\"1\">\r\n"
				+ "						<POID>0.0.0.1 /billinfo -1 0</POID>\r\n"
				+ "						<BILLINFO_ID>2 - Rental</BILLINFO_ID>\r\n"
				+ "						<PAYINFO elem=\"0\"></PAYINFO>\r\n"
				+ "						<BAL_INFO elem=\"1\"></BAL_INFO>\r\n"
				+ "						<PAY_TYPE>10001</PAY_TYPE>\r\n"
				+ "						<BILLING_SEGMENT>0</BILLING_SEGMENT>\r\n"
				+ "						<PARENT_FLAGS>0</PARENT_FLAGS>\r\n"
				+ "						<BILL_WHEN>1</BILL_WHEN>\r\n"
				+ "						<ACTG_TYPE>2</ACTG_TYPE>\r\n"
				+ "						<CURRENCY>48</CURRENCY>\r\n" + "					</BILLINFO>\r\n"
				+ "					<BILLINFO elem=\"2\">\r\n"
				+ "						<POID>0.0.0.1 /billinfo -1 0</POID>\r\n"
				+ "						<BILLINFO_ID>3 - IPTV</BILLINFO_ID>\r\n"
				+ "						<PAYINFO elem=\"0\"></PAYINFO>\r\n"
				+ "						<BAL_INFO elem=\"2\"></BAL_INFO>\r\n"
				+ "						<PAY_TYPE>10001</PAY_TYPE>\r\n"
				+ "						<BILLING_SEGMENT>0</BILLING_SEGMENT>\r\n"
				+ "						<PARENT_FLAGS>0</PARENT_FLAGS>\r\n"
				+ "						<BILL_WHEN>1</BILL_WHEN>\r\n"
				+ "						<ACTG_TYPE>2</ACTG_TYPE>\r\n"
				+ "						<CURRENCY>48</CURRENCY>\r\n" + "					</BILLINFO>\r\n"
				+ "					<BILLINFO elem=\"3\">\r\n"
				+ "						<POID>0.0.0.1 /billinfo -1 0</POID>\r\n"
				+ "						<BILLINFO_ID>4 - Utilities</BILLINFO_ID>\r\n"
				+ "						<PAYINFO elem=\"0\"></PAYINFO>\r\n"
				+ "						<BAL_INFO elem=\"3\"></BAL_INFO>\r\n"
				+ "						<PAY_TYPE>10001</PAY_TYPE>\r\n"
				+ "						<BILLING_SEGMENT>0</BILLING_SEGMENT>\r\n"
				+ "						<PARENT_FLAGS>0</PARENT_FLAGS>\r\n"
				+ "						<BILL_WHEN>1</BILL_WHEN>\r\n"
				+ "						<ACTG_TYPE>2</ACTG_TYPE>\r\n"
				+ "						<CURRENCY>48</CURRENCY>\r\n" + "					</BILLINFO>\r\n"
				+ "					<BAL_INFO elem=\"0\">\r\n"
				+ "						<POID>0.0.0.1 /balance_group -1 0</POID>\r\n"
				+ "						<BILLINFO elem=\"0\"></BILLINFO>\r\n"
				+ "						<NAME>Retail Revenue Sharing</NAME>\r\n"
				+ "						<LIMIT elem=\"1001001\">\r\n"
				+ "							<CREDIT_FLOOR>NULL</CREDIT_FLOOR>\r\n"
				+ "							<CREDIT_LIMIT>NULL</CREDIT_LIMIT>\r\n"
				+ "						</LIMIT>\r\n" + "					<LIMIT elem=\"1001002\">\r\n"
				+ "						<CREDIT_FLOOR>NULL</CREDIT_FLOOR>\r\n"
				+ "						<CREDIT_LIMIT>NULL</CREDIT_LIMIT>\r\n" + "					</LIMIT>\r\n"
				+ "					<LIMIT elem=\"1001003\">\r\n"
				+ "						<CREDIT_FLOOR>NULL</CREDIT_FLOOR>\r\n"
				+ "						<CREDIT_LIMIT>NULL</CREDIT_LIMIT>\r\n" + "					</LIMIT>\r\n"
				+ "					</BAL_INFO>\r\n" + "					<BAL_INFO elem=\"1\">\r\n"
				+ "						<POID>0.0.0.1 /balance_group -1 0</POID>\r\n"
				+ "						<BILLINFO elem=\"1\"></BILLINFO>\r\n"
				+ "						<NAME>Rental</NAME>\r\n" + "					</BAL_INFO>\r\n"
				+ "					<BAL_INFO elem=\"2\">\r\n"
				+ "						<POID>0.0.0.1 /balance_group -1 0</POID>\r\n"
				+ "						<BILLINFO elem=\"2\"></BILLINFO>\r\n"
				+ "						<NAME>IPTV</NAME>\r\n" + "					</BAL_INFO>\r\n"
				+ "					<BAL_INFO elem=\"3\">\r\n"
				+ "						<POID>0.0.0.1 /balance_group -1 0</POID>\r\n"
				+ "						<BILLINFO elem=\"3\"></BILLINFO>\r\n"
				+ "						<NAME>Utilities</NAME>\r\n"
				+ "						<LIMIT elem=\"1001010\">\r\n"
				+ "							<CREDIT_FLOOR>NULL</CREDIT_FLOOR>\r\n"
				+ "							<CREDIT_LIMIT>NULL</CREDIT_LIMIT>\r\n"
				+ "						</LIMIT>\r\n" + "					<LIMIT elem=\"1001011\">\r\n"
				+ "						<CREDIT_FLOOR>NULL</CREDIT_FLOOR>\r\n"
				+ "						<CREDIT_LIMIT>NULL</CREDIT_LIMIT>\r\n" + "					</LIMIT>\r\n"
				+ "					\r\n" + "					</BAL_INFO>\r\n"
				+ "					<PAYINFO elem=\"0\">\r\n"
				+ "						<POID>0.0.0.1 /payinfo -1 0</POID>\r\n"
				+ "						<PAY_TYPE>10001</PAY_TYPE>\r\n"
				+ "						<INV_TYPE>0</INV_TYPE>\r\n"
				+ "						<INHERITED_INFO elem=\"0\">\r\n"
				+ "							<INV_INFO elem=\"0\">\r\n"
				+ "								<ADDRESS>aaaa</ADDRESS>\r\n"
				+ "							</INV_INFO>\r\n" + "						</INHERITED_INFO>\r\n"
				+ "					</PAYINFO>\r\n" + "					<PROFILES elem=\"0\">\r\n"
				+ "						<PROFILE_OBJ>0.0.0.1 /profile/bac_rental -1 0</PROFILE_OBJ>\r\n"
				+ "						<INHERITED_INFO elem=\"0\">\r\n"
				+ "							<BAC_FLD_RENTAL elem=\"0\">\r\n"
				+ "								<BAC_FLD_RENTAL_AREA>120</BAC_FLD_RENTAL_AREA>\r\n"
				+ "							</BAC_FLD_RENTAL>\r\n" + "						</INHERITED_INFO>\r\n"
				+ "					</PROFILES>\r\n" + "					<PROFILES elem=\"1\">\r\n"
				+ "						<PROFILE_OBJ>0.0.0.1 /profile/acct_extrating -1 0</PROFILE_OBJ>\r\n"
				+ "						<INHERITED_INFO elem=\"0\">\r\n"
				+ "							<DATA_ARRAY elem=\"0\">\r\n"
				+ "								<NAME>Shop Area</NAME>\r\n"
				+ "								<VALUE>120</VALUE>\r\n"
				+ "								<VALID_FROM>0</VALID_FROM>\r\n"
				+ "								<VALID_TO>0</VALID_TO>\r\n"
				+ "							</DATA_ARRAY>\r\n" + "						</INHERITED_INFO>\r\n"
				+ "					</PROFILES>\r\n" + "					<SERVICES elem=\"0\">\r\n"
				+ "						<SERVICE_OBJ>0.0.0.1 /service/bac/retail -1 0</SERVICE_OBJ>\r\n"
				+ "						<BAL_INFO elem=\"0\"></BAL_INFO>\r\n"
				+ "						<LOGIN>Test_ahmed_002_LOGIN_RETAIL</LOGIN>\r\n"
				+ "						<DEALS elem=\"0\">\r\n"
				+ "							<DEAL_OBJ>0.0.0.1 /deal 3782842 0</DEAL_OBJ>\r\n"
				+ "						</DEALS>\r\n" + "						<DEALS elem=\"1\">\r\n"
				+ "						<DEAL_OBJ>0.0.0.1 /deal 3783866 0</DEAL_OBJ>\r\n"
				+ "					</DEALS>\r\n" + "					<DEALS elem=\"2\">\r\n"
				+ "						<DEAL_OBJ>0.0.0.1 /deal 3781818 0</DEAL_OBJ>\r\n"
				+ "					</DEALS>\r\n" + "					</SERVICES>\r\n"
				+ "					<SERVICES elem=\"1\">\r\n"
				+ "						<SERVICE_OBJ>0.0.0.1 /service/bac/rental -1 0</SERVICE_OBJ>\r\n"
				+ "						<BAL_INFO elem=\"1\"></BAL_INFO>\r\n"
				+ "						<LOGIN>Test_ahmed_002_LOGIN_RENTAL</LOGIN>\r\n"
				+ "						<DEALS elem=\"0\">\r\n"
				+ "							<DEAL_OBJ>0.0.0.1 /deal 4309250 0</DEAL_OBJ>\r\n"
				+ "						</DEALS>\r\n" + "					</SERVICES>\r\n"
				+ "					<SERVICES elem=\"2\">\r\n"
				+ "						<SERVICE_OBJ>0.0.0.1 /service/bac/iptv -1 0</SERVICE_OBJ>\r\n"
				+ "						<BAL_INFO elem=\"2\"></BAL_INFO>\r\n"
				+ "						<LOGIN>Test_ahmed_002_LOGIN_IPTV</LOGIN>\r\n"
				+ "						<DEALS elem=\"0\">\r\n"
				+ "							<DEAL_OBJ>0.0.0.1 /deal 4272156 0</DEAL_OBJ>\r\n"
				+ "						</DEALS>\r\n" + "					</SERVICES>\r\n"
				+ "					<SERVICES elem=\"3\">\r\n"
				+ "						<SERVICE_OBJ>0.0.0.1 /service/bac/util/power -1 0</SERVICE_OBJ>\r\n"
				+ "						<BAL_INFO elem=\"3\"></BAL_INFO>\r\n"
				+ "						<LOGIN>Test_ahmed_002_LOGIN_POWER</LOGIN>\r\n"
				+ "						<DEALS elem=\"0\">\r\n"
				+ "							<DEAL_OBJ>0.0.0.1 /deal 4461432 0</DEAL_OBJ>\r\n"
				+ "						</DEALS>\r\n" + "					</SERVICES>\r\n"
				+ "					<SERVICES elem=\"4\">\r\n"
				+ "						<SERVICE_OBJ>0.0.0.1 /service/bac/util/water -1 0</SERVICE_OBJ>\r\n"
				+ "						<BAL_INFO elem=\"3\"></BAL_INFO>\r\n"
				+ "						<LOGIN>Test_ahmed_002_LOGIN_WATER</LOGIN>\r\n"
				+ "						<DEALS elem=\"0\">\r\n"
				+ "							<DEAL_OBJ>0.0.0.1 /deal 4463480 0</DEAL_OBJ>\r\n"
				+ "						</DEALS>\r\n" + "					</SERVICES>\r\n"
				+ "					<ACCTINFO elem=\"0\">\r\n"
				+ "						<POID>0.0.0.1 /account -1 0</POID>\r\n"
				+ "						<BAL_INFO elem=\"0\"></BAL_INFO>\r\n"
				+ "						<ACCOUNT_NO>Test_ahmed_002_ACCOUNT_NO</ACCOUNT_NO>\r\n"
				+ "					</ACCTINFO>\r\n" + "				</PCM_OP_CUST_CREATE_CUSTOMER_inputFlist>";
		try {
			xmlResponse = serviceLocator.getBRMCustServices().pcmOpCustCreateCustomer(0, xmlRequest);
		} catch (RemoteException | ServiceException e) {
			e.printStackTrace();
		}
		return xmlResponse;
	}

}
